config/routes.rb
WhyISoFool::Application.routes.draw do
  resources :stories
  resources :comments

  get "admin/index", :as => :admin
  get "stories/:id/toggle_visiblity" => "stories#toggle_visiblity", :as => :toggle_story_visiblity

  match 'any_free' => 'stories#any_free'
  match 'vk_post/:id' => 'stories#vk_post'

  root :to => "stories#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :body
  belongs_to :story
end

app/controllers/comments_controller.rb
# encoding: UTF-8
class CommentsController < ApplicationController
  before_filter :admin_auth, :except => [:new, :create]
  # GET /comments
  # GET /comments.xml
  def index
    @comments =  Comment.paginate(
        :order => "created_at desc",
        :page => params[:page],
        :per_page => 50
    )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment, :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    if Comment.find(params[:id]).destroy
      redirect_to  :back, :notice => "Комментарий №" + params[:id] + "был успешно похерен!"
    else
      redirect_to  :back, :notice => "Что то пошло не так, комментарий не удалён!"
    end
  end
end

app/views/comments/_form.html.erb
<%= form_for :comment, @comment, :url => {:controller => "stories", :action => "add_comment", :id => @story.id}, :remote => true do |f| %>
<table width="100%">
  <tr><td align="center"><%= f.label :author, "Ваше имя(необязательно)" %></td></tr>
  <tr><td align="center"><%= f.text_field :author, :style => "width: 300px;" %></td></tr>
  <tr><td align="center"><div id="commentbody"><%= f.label :body, "Комментарий" %></div></td></tr>
  <tr><td align="center"><%= f.text_area :body, :style => "width: 300px; height: 100px;" %></td></tr>
  <tr><td align="center"><%= submit_tag "Отправить" %></td></tr>    
</table>
<% end %>

app/views/comments/_show.html.erb
<%= div_for show, :class => :hentry do %>
  <div>
    <div style="float: left">
      <%= h(show.author) %> <%= distance_of_time_in_words_to_now(show.created_at) %> назад
      <%= link_to_if (controller_name == "comments"), "написал", show.story %>
      :
    </div>
    <% if !session[:user].blank? %>
      <div class="adminmenu" style="float: right">
        <%= link_to 'Удалить комментарий', show, :method => :delete, :confirm => "Вы уверены?" %>
      </div>
    <% end %>

  </div>
  <blockquote>
    <%= show.body %>
  </blockquote>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% content_for :content do %>

    <%= render :partial => "show", :collection => @comments %>

<%= will_paginate @comments %>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>