config/routes.rb
WhyISoFool::Application.routes.draw do
  resources :stories
  resources :comments

  get "admin/index", :as => :admin
  get "stories/:id/toggle_visiblity" => "stories#toggle_visiblity", :as => :toggle_story_visiblity

  match 'any_free' => 'stories#any_free'
  match 'vk_post/:id' => 'stories#vk_post'

  root :to => "stories#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/story.rb
class Story < ActiveRecord::Base
  validates_presence_of :content
  validates_length_of :content, :minimum => 10
  has_many :comments, :order => 'created_at ASC', :dependent => :delete_all
end

app/controllers/stories_controller.rb
# encoding: UTF-8

class StoriesController < ApplicationController
  before_filter :admin_auth, :only => [ :edit, :update, :destroy, :toggle_visiblity ]
  # GET /stories
  # GET /stories.xml
  def index
    session[:page] = params[:page]
    @order = 'created_at DESC'
    @conditions = ['content like ?', "%#{params[:s]}%"] if params[:s]
    if params[:order].present? and params[:order].eql?("best")
      @order = 'rate DESC'
    end

    dead_time = case params[:period]
                  when "week"  then Time.now - 1.week
                  when "month" then Time.now - 1.month
                end

    if session[:user].blank?
      if dead_time
        @conditions = ['content like ? AND aprooved = ? AND created_at >= ?', "%#{params[:s]}%", true, dead_time]
      else
        @conditions = ['content like ? AND aprooved = ?', "%#{params[:s]}%", true]
      end
    else
      if params[:order].blank?
        @order = "aprooved DESC, " + @order
      end
    end

    @stories = Story.paginate(
        :conditions => @conditions,
        :order => @order,
        :per_page => 9,
        :page => params[:page]
    )

    respond_to do |format|
      format.html
      format.xml  { render :layout => false }
    end
  end

  def rate_up
    @story = Story.find(params[:id])
    @story.rate = @story.rate + 1
    @story.save
    session["story" + params[:id]] = true
    respond_to do |format|
      format.js { render "rate_change" }
      format.html { redirect_to get_url }
    end
  end

  # GET /stories/rate_down/1
  def rate_down
    @story = Story.find(params[:id])
    @story.rate = @story.rate - 1
    @story.save
    session["story" + params[:id]] = true
    respond_to do |format|
      format.js { render "rate_change" }
      format.html { redirect_to get_url }
    end
  end

  # GET /stories/1
  # GET /stories/1.xml
  def show
    @story = Story.includes(:comments).find(params[:id])
    @next = (@story.id.eql?(Story.last.id)) ? Story.first.id : Story.where(["id > ?", params[:id]]).limit(1).first.id
    @prev = (@story.id.eql?(Story.first.id)) ? Story.last.id : getPrev(@story.id)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end


  def any_free
    if User.authenticate(params[:username], params[:password])
      @story = Story.find_by_vk_label(false)
    end
    render 'stories/any_free', :layout => false
  end

  def vk_post
    if User.authenticate(params[:username], params[:password])
      Story.find(params[:id]).update_attribute(:vk_label, true)
    end
    render :text => "Ok"
  end

  def find
    redirect_to :controller => 'stories' , :s => params[:s], :notice => 'Результаты поиска по запросу ' + params[:s]
  end

  # POST /stories
  # POST /stories.xml
  def create
    @story = Story.new(params[:story])
    @story.vk_label = false
    if (@story.content.include? "</") or (@story.content.include? "://")
      respond_to do |format|
        format.html { render :text => "<html><head><link href='/stylesheets/theme000.css' media='screen' rel='stylesheet' type='text/css'/><script>window.setTimeout('window.top.hidePopWin()', 10000);</script></head><body><p id='notice'>Пиздуй отсюда нахуй, ёбаный спамер</p><p style='text-align: center;'>Что за хуйню ты мне тут пишешь? А??? СУКА!!!</p><div style='text-align: center;'>" + params[:story][:content] + "</div><div style='width: 300; margin: 0px auto;'><input type='button' value='Скрыть (Автоскрытие в течении 10 секунд)' onclick='window.top.hidePopWin();' class='button'/></div><p style='text-align: center;'><a href='' onclick='window.top.hidePopWin();window.open(\"http://natribu.org/\");'>Пойти нахуй</a><p></body></html>" }
      end
    else
      @story.rate = 0

      if @story.author.blank?
        @story.author = "Аноним"
      end

      respond_to do |format|
        if @story.save
#      		Thread.new do
#      			User.all.each do |user|
#      				UserMailer.createstory_confirmation(@story, user).deliver
#      			end
#      		end
          format.html { render :text => "<html><head><link href='/stylesheets/theme000.css' media='screen' rel='stylesheet' type='text/css'/><script>window.setTimeout('window.top.hidePopWin()', 10000);</script></head><body><p id='notice'>Ваша история добавлена и появиться на сайте после одобрения модератором</p><div style='text-align: center;'>" + params[:story][:content] + "</div><div style='width: 300; margin: 0px auto;'><input type='button' value='Скрыть (Автоскрытие в течении 10 секунд)' onclick='window.top.hidePopWin();' class='button'/></div><p style='text-align: center;'><a href='' onclick='window.top.hidePopWin();window.open(\"" + story_path(@story) +"\");'>Перейти на страницу истории</a><p></body></html>" }
          format.xml  { render :xml => @story, :status => :created, :location => @story }
        else
          format.html { render :text => "<html><head><link href='/stylesheets/theme000.css' media='screen' rel='stylesheet' type='text/css'/><script>window.setTimeout('window.top.hidePopWin();', 10000);</script></head><body><div style='height: 150px;'></div><p id='notice'>Ваша история слишком коротка</p><div style='width: 300; margin: 0px auto;'><input type='button' value='Скрыть (Автоскрытие в течении 10 секунд)' onclick='window.top.hidePopWin();' class='button'/></div></body></html>" }
          format.xml  { render :xml => @story.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.xml
  def update
    if (story = Story.find(params[:id])).update_attributes(params[:story])
        redirect_to story, :notice => "Story was successfully updated."
    else
        render :edit, :notice => "История не была обновлена"
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.xml
  def destroy
    Story.find(params[:id]).destroy
    redirect_to  :controller => 'stories', :notice => 'История №' + params[:id].to_s + ' была успешно запушена в космос)'
  end

  def toggle_visiblity
    Story.find(params[:id]).toggle!(:aprooved)
    redirect_to  :controller => 'stories', :notice => "Видимость истории №#{params[:id]} была успешно изменена"
  end

  def add_comment
		@comment = Comment.new(params[:comment])
    if @comment.author.blank?
      @comment.author = "Аноним"
    end
		@story = Story.find(params[:id])
		@comment.story = @story
    @saved = (@comment.save) and ((session["lastcommenttime"].blank?) or (Time.now - session["lastcommenttime"] > 60))
#    if @saved
#      Thread.new do
#        User.all.each do |user|
#          UserMailer.append_comment_notification(@comment, user).deliver
#        end
#      end
#    end

    respond_to do |format|
      format.js
      format.html { redirect_to @story }
    end
  end

  private

  def getPrev id
	  i = id.to_i
	  loop do
  		i = i - 1
  		break if (Story.where(["id = ?", i.to_s]).size > 0)
  	end
  	i.to_s
  end
end

app/controllers/story_controller.rb
class StoryController < ApplicationController
  def create
  end

  def loading
  end
end

app/views/stories/_adminmenu.html.erb
  <% if !session[:user].blank? %>
  <div class="adminmenu">
    <%= link_to 'Удалить', @story, :method => :delete, :confirm => "Точно удалить?" %> |
    <%= link_to 'Изменить', edit_story_path(@story) %> |
    <%= link_to @story.aprooved ? "Скрыть" : "Опубликовать", toggle_story_visiblity_path(@story) %>
  </div>
  <% end %>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
  <div id="newform">
    <div class="field">
      <%= f.label :author, "Автор" %>
      <%= f.text_field :author, :size => 25 %>
    </div>

    <div class="field">
      <%= f.label :content, "История" %><br/>
      <%= f.text_area :content, :style => 'width: 500px;' %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/stories/_formcreate.html.erb
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :all %>
<table>
<tr>
<td width="10"></td>
<td>
<%= form_for :story, :url => { :controller => "stories"}  do |f| %>
<table>
  <tr><td align="center"><h2 id="paragraph">Раскажи свою историю</h2></td></tr>
  <tr><td align="center"><%= f.label :author, "Ваше имя" %></td></tr>
  <tr><td align="center"><%= f.text_field :author, :size => 60 %></td></tr>
  <tr><td align="center"><%= f.label :content, "История" %></td></tr>
  <tr><td align="center"><%= f.text_area :content, :size => "62x19" %></td></tr>
  <tr><td>
    <div style="margin-top: 10px;">
      <table width="100%">
        <tr>
          <td align="center">
            <input type="button" value="Добавить" onclick="document.forms[0].submit();" class="button"/>
          </td>
          <td align="center">
            <input type="button" value="Закрыть" onclick="window.top.hidePopWin();" class="button"/>
          </td>
        </tr>
      </table>
    </div>
  </td></tr>
</table>
<% end %>
</td>
</tr>
</table>

app/views/stories/_story.html.erb
<div class="postwrap fix">
  <div class="post-36 post type-post hentry category-uncategorized" id="post-36">
    <div class="copy fix">
      <div class="post-header fix post-nothumb">
        <div class="post-title-section fix">
          <div class="post-title fix">
            <div style="float: left">
              <%= link_to "#" + story.id.to_s + ", добавлена " + distance_of_time_in_words_to_now(story.created_at) + " назад" , { :action => 'show', :id => story.id } %>
            </div>
            <div class="metabar" style="float:right;">
              <em>
                  Автор: <%= story.author %>
              </em>
            </div>
            <div class="clear"></div>
          </div>
        </div>
      </div>      
    </div>
    <hr/>
    <div class="copy fix">
      <div class="textcontent">
        <p>
            <% if action_name.eql?("show") %>
              <%= story.content %>
            <% else %>
              <%= truncate(story.content, :length => 1024) %>
            <% end %>
        </p>
        <% @story_vote_id = "story" + story.id.to_s %>
        <% @story = story %>
        <%= render :partial => 'adminmenu' %>
      </div>
    </div>
    <div class="hl"></div>
    <div class="post-footer">
      <div class="left" id="<%= @story_vote_id %>">
        <% if session[@story_vote_id].blank? %>
            <%= link_to "Ты дура(+)", { :action => 'rate_up', :id => story.id }, :remote => true %>
        <% else %>
            Рейтинг:
        <% end %>
          <span>
            <%= story.rate.to_s %>
          </span>
        <% if session[@story_vote_id].blank? %>
          <%= link_to "Лажа(-)", { :action => 'rate_down', :id => story.id }, :remote => true %>
        <% end %>
      </div>
      <% if !action_name.eql?("show") %>
        <div class="commentscount">
			<span>
			  <%= story.comments.count %>
			</span>
			комментариев
        </div>
        <div id="more"><%= link_to "Далее", { :action => 'show', :id => story.id } %></div>
      <% else %>
        <div id="vklike">
			<div id="vk_like"></div>
			<script type="text/javascript">
				VK.Widgets.Like("vk_like", {type: "button"});
			</script>
        </div>
	    <div id="share">
		  <div class="yashare-auto-init" data-yashareType="button" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,lj"></div> 
		</div>
	  <% end %>
      <div class="clear"></div>
    </div>
  </div><!--post -->
</div>
<div class="tags"></div>
<div class="clear"></div>

app/views/stories/add_comment.js.erb
<% if @saved %>
    <% session["lastcommenttime"] = Time.now %>
    comment_notify("<p id='notice'>Ваш комментарий был успешно добавлен!</p>");
    $("#commentbody").val("Комментарий");
    $("#comments").append("<%= escape_javascript(render :partial => "comments/show", :collection => [@comment]) %>");
    var comment_div = $("#<%= dom_id @comment %>");
    comment_div.hide().slideToggle("slow");
    $("#comment_body").val("");
    $("#comment_author").val("");
<% else %>
    $("#commentbody").val("Комментарий");
    <% if (session["lastcommenttime"].blank?) or (Time.now - session["lastcommenttime"] > 10) %>
        $("#comment_body").val("<p id='commentbodyerror'>Комментарий (напиши что-нибудь!)</p>");
    <% else %>
        comment_notify("<p id='notice' style='color: red;'>Не сри в комментах!(Писать можно только раз в минуту)</p>");
    <% end %>
<% end %>

app/views/stories/any_free.html.erb
<%= link_to @story.id, story_url(@story) %>
<label>
  <%= @story.content %>
</label>

app/views/stories/edit.html.erb
<% content_for :content do %>
  <div class="adminmenu">
    <h1>Измени историю</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @story %> |
    <%= link_to 'Back', stories_path %>
  </div>
<% end %>

app/views/stories/index.html.erb
<% content_for :content do %>
    <% @stories.each_with_index do |story,index| %>
        <%= render :partial => 'story', :collection => [story] %>
        <% if index == 1 %>
            <%= render :partial => "advert/google_adsence_468_60" %>
        <% end %>
    <% end %>
    <% p "fuck" %>
    <h1 id="pagination">
      <%= will_paginate @stories, :previous_label => "← сюда", :next_label => "туда →", :inner_window => 1, :outer_window => 2 %>
    </h1>
<% end %>

app/views/stories/new.html.erb
<% content_for :content do %>
<div class="fi">
  <div class="fi_text">
    <h1>New story</h1>

    <%= render 'form' %>

    <%= link_to 'Back', stories_path %>
  </div>
</div>
<% end %>

app/views/stories/rate_change.js.erb
$("#story<%= @story.id %>").html('<div class="ajaxanswer">Ваш голос принят</div>');

app/views/stories/show.html.erb
<% content_for :head do %>
  <script type="text/javascript" src="http://userapi.com/js/api/openapi.js?22"></script>
  <script type="text/javascript">
    VK.init({apiId: 2237171, onlyWidgets: true});
  </script>
  <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
<% end %>
<% content_for :content do %>
  <%= render :partial => 'story', :collection => [ @story ] %>
    <div id="pagination">
		<table width="100%">
			<tr>
				<td>
					<h2 id="paragraph" style="text-align: left;">
						<%= link_to "← предыдущая", { :action => 'show', :id => @prev } %>
					</h2>
				</td>
				<td>
					<h2 id="paragraph">
						<%= link_to "назад", { :action => 'index', :page => session[:page]} %>
					</h2>
				</td>
				<td>
					<h2 id="paragraph" style="text-align: right;">
						<%= link_to "следующая →", { :action => 'show', :id => @next } %>
					</h2>
				</td>
			</tr>
		</table>
    </div>
	
  <div id="commentsblock" style="margin-top: 40px; margin-bottom: 40px;">
    <div id="comments">
        <%= render :partial => "comments/show", :collection => @story.comments %>
    </div>
    <div id="commentnotice">
    </div>
    <div>
        <%= render :partial => "comments/form" %>
    </div>
    <div id="vk_comments"></div>
	<script type="text/javascript">
		VK.Widgets.Comments("vk_comments", {limit: 10, width: "640", attach: "*"});
	</script>
  </div>
<% end %>